### ISSUE TITLE
Any Affiliated Papers?

### ISSUE THREAD

**Issue by Ezharjan** [BeckerZhang/SUMO_Project#1]
Are there any affiliated papers with this project? 

Both for citation and a better understanding of the details of the code.

**Comment by BeckerZhang** [comment]
Sorry, there is no affiliated paper until now and the only thing I can provide is the project code. I believe that the layout of auto.py would be helpful for your understanding.

**Comment by Ezharjan** [comment]
> Sorry, there is no affiliated paper until now and the only thing I can provide is the project code. I believe that the layout of auto.py would be helpful for your understanding.

Thanks!
